### ISSUE TITLE
Polnjenje tabel

### ISSUE THREAD

**Issue by MasaOrelj** [MasaOrelj/Svecano-prisegam-da-imam-nekaj-za-bregom#1]
Poskusili smo uvoziti podatke v tabelo professor v sql s funkcijo uvozi_v_sql, ampak nam javlja warning (setting with copy warning) in tabele v sql ne napolni. Ali imate kakšen nasvet, kako bi težavo odpravili?
Hvala :)

**Comment by pavlanovak** [comment]
Smo popravili
