### ISSUE TITLE
Dodajanje jpg oz. png slik

### ISSUE THREAD

**Issue by MasaOrelj** [MasaOrelj/Svecano-prisegam-da-imam-nekaj-za-bregom#4]
Ko shranimo sliko v naš repozitorij in jo dodamo v professors.html, je v naši aplikaciji ne prikaže. Probala sem že veliko različnih poti do slike, jo premikala po repozitoriju, nastavila v nastavitvah unblock, ampak nič ne deluje. Bi lahko pogledali, kje je težava?

**Comment by majbc1999** [comment]
Živjo,

slike je potrebno dodajati s pomočjo funkcije `url`. V `aplikacija.py` boste morali dodati:

```python
static_dir = "./images"

@route("/images/<filename:path>") 
def static(filename):
    return static_file(filename, root=static_dir)
```

Sliko v htmlju potem kličete na naslednji način:
```html
<img src={{url('static', filename='ss3.png')}} class="card-img-top">
```

**Comment by MasaOrelj** [comment]
Hvala, sem popravila in deluje.
