### ISSUE TITLE
Forum komentarji

### ISSUE THREAD

**Issue by pavlanovak** [MasaOrelj/Svecano-prisegam-da-imam-nekaj-za-bregom#5]
Pozdravljeni!

Uspelo nam je narediti forum poste, ki se tudi shranijo v bazo in izpišejo (aplikacija.py in forum.html). Pojavi pa se problem, ko hočemo nekako povezati komentarje in poste, saj ne vemo, kako dobiti post_id, na katerega je navezan comment. Post_id je v naši tabeli foreign key. 
Kakršna koli pomoč bi nam prišla prav. Hvala.

**Comment by majbc1999** [comment]
Živjo, 

zaenkrat nimam dostopa do vašega projekta, saj na nekaj mestih v vaši aplikaciji uporabljate datoteko `auth.py`. Aplikacija mora delovati izključno z uporabo datoteke `auth_public.py`, kjer so podatki za prijavo javnosti. Vaše prijavne podatke uporabljajte samo tam, kjer delate posebne stvari s tabelami (npr. kreirate tabele). 

Preden bo lahko uporabnik `javnost` (iz `auth_public`) uporabljal vašo aplikacijo, mu morate seveda nastaviti dovoljenja (glejte kako so to naredili v drugih projektih, npr. [tukaj](https://github.com/sarazuzek/Pomocnik-za-trgovanje/blob/main/trgovanje.sql)). Ko boste imeli to popravljeno, mi javite, da vam lahko pomagam z zgornjim problemom.

**Comment by pavlanovak** [comment]
zivijo,
zdaj bi moralo delati.

**Comment by majbc1999** [comment]
Živjo,

najlažje komentar in forum povežete tako, da v tabelo `comment` dodate stolpec (npr. po imenu `forum`), kamor potem shranjujete `id` foruma, na katerega bo komentar vezan. Seveda naj bo stolpec tipa `FOREIGN KEY` na `forum(id)`.

**Comment by pavlanovak** [comment]
Zivjo,
imamo vbistvu narejeno tako, kot ste rekli, samo ne vemo, kako mu 'avtomatsko' povemo, na kateri post je vezan komentar, torej kako dobiti id vrednost posta, na katerega se nanasa komentar, in jo potem shraniti v stolpec, katerega vrednosti so foreign key.
Hvala in lep dan

**Comment by majbc1999** [comment]
Živjo,

se opravičujem za pozen odgovor, bil sem precej zaposlen s svojimi izpiti v tem tednu.

Torej, najprej naj vas opozorim, da sem pri registraciji dobil napako (očitno izbira leva za ljubljenčka res ni najbolj pametna 😂):

```cmd
Traceback (most recent call last):
  File "D:\Sola\MAGISTERIJ\4. semester\Osnove podatkovnih baz\projekti\Svecano-prisegam-da-imam-nekaj-za-bregom\bottle.py", line 1005, in _handle
    out = route.call(**args)
  File "D:\Sola\MAGISTERIJ\4. semester\Osnove podatkovnih baz\projekti\Svecano-prisegam-da-imam-nekaj-za-bregom\bottle.py", line 2017, in wrapper
    rv = callback(*a, **ka)
  File "D:\Sola\MAGISTERIJ\4. semester\Osnove podatkovnih baz\projekti\Svecano-prisegam-da-imam-nekaj-za-bregom\bottleext.py", line 15, in decorator
    return callback(*largs, **kwargs)
  File "D:\Sola\MAGISTERIJ\4. semester\Osnove podatkovnih baz\projekti\Svecano-prisegam-da-imam-nekaj-za-bregom\aplikacija.py", line 118, in registracija_post
    house_id = dodaj_house(question1, question2, question3, question4, question5)
  File "D:\Sola\MAGISTERIJ\4. semester\Osnove podatkovnih baz\projekti\Svecano-prisegam-da-imam-nekaj-za-bregom\aplikacija.py", line 89, in dodaj_house
    house_scores[question3] += 1
KeyError: 'lion'
```
Napaka ni nič posebnega, samo v formsih morate popraviti value-je za vprašanja 3-5 (tako kot že imate vprašanja 1 in 2).


Glede vprašanja zgoraj... če prav razumem, želite omogočiti komeniranje pod vsakim postom. Komentar se nato shrani (skupaj z id-jem posta) in izpiše pod tem določenim postom.

To se naredi tako, da se funkciji `comment_post` pošlje še parameter, ki bo v tem primeru id pripadajočega posta. Še prej boste morali spremeniti routo, saj sta trenutno `forum_post` in `comment_post` obe na `/forum`.

```python
@post('/comment/<post_id:int>')   # v naslov route specificiramo parameter 
@cookie_required
def comment_post(post_id: str):  # funkciji dodamo parameter `post_id`
    uporabnik = request.get_cookie("username")
    cur.execute("""SELECT * FROM Student WHERE "Username" = %s""", [uporabnik])
    lst = cur.fetchall()[0]
    id_user = lst[0]
    username = lst[1]
    content_comment = request.forms.get('content')
    cur.execute(""" INSERT INTO comment (text, student_id, post_id) 
                    VALUES (%s, %s, %s)""", (content_comment, id_user, int(post_id)))
    conn.commit()
    redirect("/forum")
```

Sedaj moramo še v htmlju vsak komentar preusmeriti na zgornjo funkcijo in ji podati pravilen parameter (torej pripadajoči `post_id`). Pomagali si bomo s funkcijo `url`. 

```html
    <h2>Posts:</h2>
    % for post in posts:
        <div>
            <p>{{ post[1] }}</p>
            <form action="{{url('comment_post', post_id=post[0])}}" method="POST">
                <textarea name="content" placeholder="Write a comment..." required></textarea>
                <br>
                <input type="submit" value="Comment">
            </form>
        </div>
        <hr>
        h3>Comments:</h3>
        % if post[0] in comments:
            % for comment in comments[post[0]]:
                <p>{{ comment }}</p>
            % end
        % end
    </div>
    <hr>
    % end
```

Za konec naj vas opozorim, da preusmeritve zaenkrat ne delate pravilno. Namreč `redirect("/forum")` lokalno deluje, ko pa boste na koncu projekt morali zagnati v Binderju, ne bo več delovalo. Zato se držite naslednjih navodil:

- v `aplikacija.py`, kjer delate preusmeritve je potrebno uporabiti funkcijo `url` (vsi redirecti morajo uporabiti `url`)
- v vseh htmljih, kjer delate preusmeritve (ali pa pošiljate forme), je prav tako potrebno uporabiti funkcijo `url` (glej kako sem naredil zgoraj)
- v funkcijo `url` ne pošiljajte poti, temveč ime pripadajoče funkcije v `aplikacija.py`. Namesto npr. `redirect(url('/forum'))`, je potrebno uporabiti `redirect(url('post_get'))`.

**Comment by pavlanovak** [comment]
Zivijo,

v imenu skupine bi se vam rada zelo zahvalila za vas cas in pomoc, nam je zelo pomagalo.
Hvala ☺️
