### ISSUE TITLE
Zaključek projekta

### ISSUE THREAD

**Issue by pavlanovak** [MasaOrelj/Svecano-prisegam-da-imam-nekaj-za-bregom#6]
Pozdravljeni, 
radi bi zaključili s projektom. Poskusili smo narediti binder, ampak daje 500: internal server error. Žal nam ni jasno, kaj ne dela. Projekt pa se nam zdi, da je končan.
Hvala

**Comment by majbc1999** [comment]
Živjo, sem sedaj porabil veliko časa za Binder, pa mi ni uspelo nič pametnega popraviti. Ali imaš ti kakšno idejo, @gasperxy?

Kar se tiče projekta vse dela in je super, popravite edino še šumnike v forumu.

**Comment by pavlanovak** [comment]
Živijo,

hvala,
smo popravili še šumnike v forumu.

**Comment by majbc1999** [comment]
Živjo, torej potrjujem projekt (@jaanos)

**Comment by pavlanovak** [comment]
Živijo,
hvala še enkrat za pomoč, smo pa sicer že tudi imeli zagovor in je vse že zaključeno 😄
